sudo: required
services:
    - docker


before_install:
    - docker build -t nikhilkataria19/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nikhilkataria19/docker-react npm run test -- --coverage

language: generic 

#amazon elastic bean stalk configuration
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-552983455595"
    bucket_path: "docker react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
    

